services:

    smartgear.command.backup.abstract:
        class: WEM\SmartgearBundle\Command\Backup\AbstractBackupCommand
        arguments:
            $backupManager : '@smartgear.backup.backup_manager'
            $framework: '@contao.framework'
        public: true

    smartgear.command.backup.create:
        class: WEM\SmartgearBundle\Command\Backup\BackupCreateCommand
        arguments:
            $backupManager : '@smartgear.backup.backup_manager'
            $framework: '@contao.framework'
        tags:
            - { name: 'console.command'}
        public: true

    smartgear.command.backup.list:
        class: WEM\SmartgearBundle\Command\Backup\BackupListCommand
        arguments:
            $backupManager : '@smartgear.backup.backup_manager'
            $framework: '@contao.framework'
        tags:
            - { name: 'console.command'}
        public: true

    smartgear.command.backup.restore:
        class: WEM\SmartgearBundle\Command\Backup\BackupRestoreCommand
        arguments:
            $backupManager : '@smartgear.backup.backup_manager'
            $framework: '@contao.framework'
        tags:
            - { name: 'console.command'}
        public: true

    smartgear.command.backup.delete:
        class: WEM\SmartgearBundle\Command\Backup\BackupDeleteCommand
        arguments:
            $backupManager : '@smartgear.backup.backup_manager'
            $framework: '@contao.framework'
        tags:
            - { name: 'console.command'}
        public: true