services:
    smartgear.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\EventListener\ReplaceInsertTagsListener
        arguments:
            $listeners:
                - '@smartgear.backend.component.core.listener.replace_insert_tags'
                - '@smartgear.backend.component.blog.listener.replace_insert_tags'
                - '@smartgear.backend.component.events.listener.replace_insert_tags'
        public: true

    smartgear.listener.load_data_container:
        class: WEM\SmartgearBundle\EventListener\LoadDataContainerListener
        arguments:
            $translator: '@contao.translation.translator'
            $framwayConfigurationManager: '@smartgear.config.manager.framway'
            $framwayThemeConfigurationManager: '@smartgear.config.manager.framway_theme'
            $listeners:
                - '@smartgear.backend.component.blog.listener.load_data_container'
                - '@smartgear.backend.component.events.listener.load_data_container'
        public: true
        
    smartgear.listener.generate_breadcrumb:
        class: WEM\SmartgearBundle\EventListener\GenerateBreadcrumbListener
        arguments:
            $listeners:
                - '@smartgear.backend.component.blog.listener.generate_breadcrumb'
                - '@smartgear.backend.component.events.listener.generate_breadcrumb'
        public: true
        
    smartgear.listener.initialize_system:
        class: WEM\SmartgearBundle\EventListener\InitializeSystemListener
        arguments:
            $templateFinder: '@smartgear.classes.template_finder'
        public: true
        
    smartgear.listener.news_list_fetch_items:
        class: WEM\SmartgearBundle\EventListener\NewsListFetchItemsListener
        public: true
        
    smartgear.listener.news_list_count_items:
        class: WEM\SmartgearBundle\EventListener\NewsListCountItemsListener
        public: true
        
    smartgear.listener.get_all_events:
        class: WEM\SmartgearBundle\EventListener\GetAllEventsListener
        public: true




        