services:
    smartgear.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\EventListener\ReplaceInsertTagsListener
        arguments:
            $listeners:
                - '@smartgear.backend.component.core.listener.replace_insert_tags'
                - '@smartgear.backend.component.blog.listener.replace_insert_tags'
                - '@smartgear.backend.component.events.listener.replace_insert_tags'
                - '@smartgear.backend.component.faq.listener.replace_insert_tags'
                - '@smartgear.backend.module.extranet.listener.replace_insert_tags'
                - '@smartgear.backend.module.form_data_manager.listener.replace_insert_tags'
        public: true

    smartgear.listener.load_data_container:
        class: WEM\SmartgearBundle\EventListener\LoadDataContainerListener
        arguments:
            $translator: '@contao.translation.translator'
            $framwayConfigurationManager: '@smartgear.config.manager.framway'
            $framwayThemeConfigurationManager: '@smartgear.config.manager.framway_theme'
            $listeners:
                - '@smartgear.backend.component.core.listener.load_data_container'
                - '@smartgear.backend.component.blog.listener.load_data_container'
                - '@smartgear.backend.component.events.listener.load_data_container'
                - '@smartgear.backend.component.faq.listener.load_data_container'
                - '@smartgear.backend.module.extranet.listener.load_data_container'
                - '@smartgear.backend.module.form_data_manager.listener.load_data_container'
        public: true
        
    smartgear.listener.generate_breadcrumb:
        class: WEM\SmartgearBundle\EventListener\GenerateBreadcrumbListener
        arguments:
            $listeners:
                - '@smartgear.backend.component.blog.listener.generate_breadcrumb'
                - '@smartgear.backend.component.events.listener.generate_breadcrumb'
        public: true
        
    smartgear.listener.initialize_system:
        class: WEM\SmartgearBundle\EventListener\InitializeSystemListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $templateFinder: '@smartgear.classes.template_finder'
        public: true
        
    smartgear.listener.news_list_fetch_items:
        class: WEM\SmartgearBundle\EventListener\NewsListFetchItemsListener
        public: true
        
    smartgear.listener.news_list_count_items:
        class: WEM\SmartgearBundle\EventListener\NewsListCountItemsListener
        public: true
        
    smartgear.listener.get_all_events:
        class: WEM\SmartgearBundle\EventListener\GetAllEventsListener
        public: true
        
    smartgear.listener.create_new_user:
        class: WEM\SmartgearBundle\EventListener\CreateNewUserListener
        arguments:
            $listeners:
                - '@smartgear.backend.component.core.listener.create_new_user'
        public: true

    smartgear.listener.personal_data_ui:
        class: WEM\SmartgearBundle\EventListener\PersonalDataManager\UiListener
        arguments:
            $translator: '@contao.translation.translator'
            $personalDataManagerUi: '@wem.personal_data_manager.service.personal_data_manager_ui'
        public: true

    smartgear.listener.personal_data_csv_formatter:
        class: WEM\SmartgearBundle\EventListener\PersonalDataManager\CsvFormatterListener
        arguments:
            $translator: '@contao.translation.translator'
        public: true

    smartgear.listener.personal_data_export:
        class: WEM\SmartgearBundle\EventListener\PersonalDataManager\ExportListener
        arguments:
            $translator: '@contao.translation.translator'
        public: true

    smartgear.listener.personal_data_anonymize:
        class: WEM\SmartgearBundle\EventListener\PersonalDataManager\AnonymizeListener
        arguments:
            $translator: '@contao.translation.translator'
        public: true

    smartgear.listener.personal_data_manager:
        class: WEM\SmartgearBundle\EventListener\PersonalDataManager\ManagerListener
        arguments:
            $translator: '@contao.translation.translator'
        public: true

    smartgear.listener.process_form_data:
        class: WEM\SmartgearBundle\EventListener\ProcessFormDataListener
        arguments:
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $listeners:
                - '@smartgear.backend.module.form_data_manager.listener.process_form_data'
        public: true

    smartgear.listener.compile_form_fields:
        class: WEM\SmartgearBundle\EventListener\CompileFormFieldsListener
        arguments:
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $listeners:
                - '@smartgear.backend.component.core.listener.compile_form_fields'
                - '@smartgear.backend.module.form_data_manager.listener.compile_form_fields'
        public: true

    smartgear.listener.security.interactive_login:
        class: WEM\SmartgearBundle\EventListener\Security\InteractiveLoginListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $scopeMatcher: '@smartgear.classes.scope_matcher'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
        public: true

    smartgear.listener.generate_page:
        class: WEM\SmartgearBundle\EventListener\GeneratePageListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $scopeMatcher: '@smartgear.classes.scope_matcher'
            $customLanguageFileLoader : '@smartgear.classes.custom_language_file_loader'
        public: true

    smartgear.listener.get_content_element:
        class: WEM\SmartgearBundle\EventListener\GetContentElementListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.listener.get_frontend_module:
        class: WEM\SmartgearBundle\EventListener\GetFrontendModuleListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.listener.backend_menu_build:
        class: WEM\SmartgearBundle\EventListener\BackendMenuBuildListener
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build }
        public: true

    smartgear.listener.load_language_file:
        class: WEM\SmartgearBundle\EventListener\LoadLanguageFileListener
        arguments:
            $customLanguageFileLoader : '@smartgear.classes.custom_language_file_loader'
        public: true    