services:
    smartgear.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\EventListener\ReplaceInsertTagsListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true
    smartgear.listener.load_data_container:
        class: WEM\SmartgearBundle\EventListener\LoadDataContainerListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true
    smartgear.listener.generate_breadcrumb:
        class: WEM\SmartgearBundle\EventListener\GenerateBreadcrumbListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true


        