services:

  smartgear.migrations.v1_0_0.m202203231730.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_0\M202203231730\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $configurationFramwayCombinedManager: '@smartgear.config.manager.framway_combined'
    public: true

  smartgear.migrations.v1_0_0.m202205130814.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_0\M202205130814\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_1.m202301050800.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_1\M202301050800\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_2.m202301051700.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_2\M202301051700\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_3.m202301100950.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_3\M202301100950\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $templatesSmartgearSynchronizer: '@smartgear.classes.directories_synchronizer.templates.smartgear'
    public: true

  smartgear.migrations.v1_0_4.m202301110935.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_4\M202301110935\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true