services:

  smartgear.migrations.v1_0_0.m202203231730.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_0\M202203231730\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $configurationFramwayCombinedManager: '@smartgear.config.manager.framway_combined'
    public: true

  smartgear.migrations.v1_0_0.m202205130814.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_0\M202205130814\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_1.m202301050800.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_1\M202301050800\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_2.m202301051700.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_2\M202301051700\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_3.m202301100950.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_3\M202301100950\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $templatesSmartgearSynchronizer: '@smartgear.classes.directories_synchronizer.templates.smartgear'
    public: true

  smartgear.migrations.v1_0_4.m202301110935.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_4\M202301110935\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $templatesSmartgearSynchronizer: '@smartgear.classes.directories_synchronizer.templates.smartgear'
    public: true

  smartgear.migrations.v1_0_5.m202301131435.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_5\M202301131435\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $templatesSmartgearSynchronizer: '@smartgear.classes.directories_synchronizer.templates.smartgear'
    public: true

  smartgear.migrations.v1_0_7.m202303291542.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_7\M202303291542\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_8.m202303291542.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_8\M202303291542\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_9.m202305012112.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_9\M202305012112\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_10.m202305311835.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_10\M202305311835\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_11.m202306152248.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_11\M202306152248\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_12.m202306231015.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_12\M202306231015\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_13.m202306271601.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_13\M202306271601\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_14.m202307061615.migration:
    class: WEM\SmartgearBundle\Migrations\V1_0_14\M202307061615\Migration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
    public: true

  smartgear.migrations.v1_0_15.m202307171545.migration:
    class: WEM\SmartgearBundle\Migrations\PlaceholderMigration
    arguments:
      $connection: '@database_connection'
      $translator: '@contao.translation.translator'
      $coreConfigurationManager: '@smartgear.config.manager.core'
      $versionComparator: '@smartgear.classes.version.comparator'
      $x: 1
      $y: 0
      $z: 15
    public: true







