services:
    ############ EXTRANET ############
    
    smartgear.backend.module.extranet.block:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\Block
        arguments:
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $configurationStepManager: '@smartgear.backend.module.extranet.configuration_step_manager'
            $resetStepManager: '@smartgear.backend.module.extranet.reset_step_manager'
            $dashboard: '@smartgear.backend.module.extranet.dashboard'
        public: true

    smartgear.backend.module.extranet.resetter:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\Resetter
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
        public: true

    smartgear.backend.module.extranet.configuration_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ConfigurationStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
            $stepSessionKey: 'sg_extranet_install_step'
            $steps: 
                - '@smartgear.backend.module.extranet.configuration_step.general'
        public: true

    smartgear.backend.module.extranet.configuration_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ConfigurationStep\General
        arguments:
            $module: 'extranet'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $commandUtil: '@smartgear.classes.command.util'
            $htmlDecoder: '@contao.string.html_decoder'
        public: true

    smartgear.backend.module.extranet.dashboard:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\Dashboard
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
        public: true

    smartgear.backend.module.extranet.reset_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ResetStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
            $stepSessionKey: 'sg_core_reset_step'
            $steps: 
                - '@smartgear.backend.module.extranet.reset_step.general'
        public: true

    smartgear.backend.module.extranet.reset_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ResetStep\General
        arguments:
            $module: 'extranet'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $resetter: '@smartgear.backend.module.extranet.resetter'
        public: true

    smartgear.backend.module.extranet.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\EventListener\ReplaceInsertTagsListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.extranet.listener.load_data_container:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\EventListener\LoadDataContainerListener
        arguments:
            $security: '@security.helper'
            $coreConfigurationManager: '@smartgear.config.manager.core'
            $dcaManipulator: '@smartgear.classes.dca.manipulator'
        public: true

    ############ FORM DATA MANAGER ############
    
    smartgear.backend.module.form_data_manager.block:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\Block
        arguments:
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $configurationStepManager: '@smartgear.backend.module.form_data_manager.configuration_step_manager'
            $resetStepManager: '@smartgear.backend.module.form_data_manager.reset_step_manager'
            $dashboard: '@smartgear.backend.module.form_data_manager.dashboard'
        public: true

    smartgear.backend.module.form_data_manager.configuration_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\ConfigurationStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'form_data_manager'
            $type: 'module'
            $stepSessionKey: 'sg_form_data_manager_install_step'
            $steps: 
                - '@smartgear.backend.module.form_data_manager.configuration_step.general'
        public: true

    smartgear.backend.module.form_data_manager.configuration_step.general:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\ConfigurationStep\General
        arguments:
            $module: 'form_data_manager'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $commandUtil: '@smartgear.classes.command.util'
            $htmlDecoder: '@contao.string.html_decoder'
        public: true

    smartgear.backend.module.form_data_manager.dashboard:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\Dashboard
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'form_data_manager'
            $type: 'module'
        public: true

    smartgear.backend.module.form_data_manager.reset_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\ResetStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'form_data_manager'
            $type: 'module'
            $stepSessionKey: 'sg_core_reset_step'
            $steps: 
                - '@smartgear.backend.module.form_data_manager.reset_step.general'
        public: true

    smartgear.backend.module.form_data_manager.reset_step.general:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\ResetStep\General
        arguments:
            $module: 'form_data_manager'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.form_data_manager.backend_controller:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\BackendController
        arguments:
            $module: 'form_data_manager'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
        public: true


    smartgear.backend.module.form_data_manager.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\EventListener\ReplaceInsertTagsListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.form_data_manager.listener.load_data_container:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\EventListener\LoadDataContainerListener
        arguments:
            $security: '@security.helper'
            $coreConfigurationManager: '@smartgear.config.manager.core'
            $dcaManipulator: '@smartgear.classes.dca.manipulator'
        public: true

    smartgear.backend.module.form_data_manager.listener.backend_menu_build:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\EventListener\BackendMenuBuildListener
        arguments:
            $translator: '@contao.translation.translator'
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, method: __invoke }

    smartgear.backend.module.form_data_manager.listener.process_form_data:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\EventListener\ProcessFormDataListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
            $routingCandidates: '@contao.routing.candidates'
        public: true
        
    smartgear.backend.module.form_data_manager.listener.compile_form_fields:
        class: WEM\SmartgearBundle\Backend\Module\FormDataManager\EventListener\CompileFormFieldsListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true
