services:
  ############ FAQ ############
    
    smartgear.backend.module.extranet.block:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\Block
        arguments:
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $configurationStepManager: '@smartgear.backend.module.extranet.configuration_step_manager'
            $resetStepManager: '@smartgear.backend.module.extranet.reset_step_manager'
            $dashboard: '@smartgear.backend.module.extranet.dashboard'
        public: true

    smartgear.backend.module.extranet.configuration_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ConfigurationStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
            $stepSessionKey: 'sg_extranet_install_step'
            $steps: 
                - '@smartgear.backend.module.extranet.configuration_step.general'
        public: true

    smartgear.backend.module.extranet.configuration_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ConfigurationStep\General
        arguments:
            $module: 'extranet'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
            $commandUtil: '@smartgear.classes.command.util'
        public: true

    smartgear.backend.module.extranet.dashboard:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\Dashboard
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
        public: true

    smartgear.backend.module.extranet.reset_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ResetStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $translator: '@contao.translation.translator'
            $module: 'extranet'
            $type: 'module'
            $stepSessionKey: 'sg_core_reset_step'
            $steps: 
                - '@smartgear.backend.module.extranet.reset_step.general'
        public: true

    smartgear.backend.module.extranet.reset_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\ResetStep\General
        arguments:
            $module: 'extranet'
            $type: 'module'
            $translator: '@contao.translation.translator'
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.extranet.listener.replace_insert_tags:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\EventListener\ReplaceInsertTagsListener
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.extranet.listener.load_data_container:
        class: WEM\SmartgearBundle\Backend\Module\Extranet\EventListener\LoadDataContainerListener
        arguments:
            $security: '@security.helper'
            $coreConfigurationManager: '@smartgear.config.manager.core'
            $dcaManipulator: '@smartgear.classes.dca.manipulator'
        public: true