services:

    # smartgear.backend.backupservice:
    #     class: WEM\SmartgearBundle\Backup\BackupService
    #     arguments:
    #         - '@contao.framework'
    #         - '@filesystem'
    #         - '@contao.slug.generator'
    #         - '@request_stack'
    #     public: true
    # smartgear.backend.updater:
    #     class: WEM\SmartgearBundle\Updater\UpdaterService
    #     arguments:
    #         - '@contao.framework'
    #         - '@filesystem'
    #         - '@contao.slug.generator'
    #         - '@request_stack'
    #     public: true

    smartgear.backend.smartgear:
        class: WEM\SmartgearBundle\Backend\Smartgear
        public: true

    smartgear.classes.directories_synchronizer.templates.rsce:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates/rsce'
            $destinationDirectory: 'templates/rsce'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.templates.smartgear:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates/smartgear'
            $destinationDirectory: 'templates/smartgear'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.templates.general:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates'
            $destinationDirectory: 'templates'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: false
        public: true

    smartgear.classes.directories_synchronizer.tiny_mce.plugins:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/assets/tinymce4/js/plugins'
            $destinationDirectory: 'assets/tinymce4/js/plugins'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.outdated_browser:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/files/vendor/outdatedbrowser'
            $destinationDirectory: 'assets/outdatedbrowser'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.tarte_au_citron:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $translator: '@contao.translation.translator'
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/files/vendor/tarteaucitron'
            $destinationDirectory: 'assets/tarteaucitron'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.config.manager.core:
        class: WEM\SmartgearBundle\Classes\Config\Manager\ManagerJson
        arguments:
            $translator: '@contao.translation.translator'
            $configuration: '@smartgear.config.core'
            $configurationFilePath: './assets/smartgear/config_core.json'
        public: true

    smartgear.classes.analyzer.htaccess:
        class: WEM\SmartgearBundle\Classes\Analyzer\Htaccess
        arguments:
            $htAccessFilePath: './.htaccess'
        public: true

    smartgear.classes.api.security.api_key:
        class: WEM\SmartgearBundle\Classes\Api\Security\ApiKey
        arguments:
            $framework: '@contao.framework'
            $coreConfigurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.classes.api.security.token:
        class: WEM\SmartgearBundle\Classes\Api\Security\Token
        arguments:
            $framework: '@contao.framework'
        public: true

    smartgear.classes.version.version:
        class: WEM\SmartgearBundle\Classes\Version\Version
        public: true

    smartgear.classes.version.comparator:
        class: WEM\SmartgearBundle\Classes\Version\Comparator
        public: true

    smartgear.classes.command.util:
        class: WEM\SmartgearBundle\Classes\Command\Util
        arguments:
            $rootDir: '%kernel.project_dir%'
        public: true

    smartgear.classes.util_framway:
        class: WEM\SmartgearBundle\Classes\UtilFramway
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $configurationThemeManager: '@smartgear.config.manager.framway_theme'
            $commandUtil: '@smartgear.classes.command.util'
        public: true

    smartgear.classes.template_finder:
        class: WEM\SmartgearBundle\Classes\TemplateFinder
        arguments:
            $projectDir: '%kernel.project_dir%'
            $configurationManager : '@smartgear.config.manager.core'
        public: true

    smartgear.config.manager.framway:
        class: WEM\SmartgearBundle\Config\Manager\Framway
        arguments:
            $translator: '@contao.translation.translator'
            $configuration: '@smartgear.config.framway'
            $configurationManagerCore: '@smartgear.config.manager.core'
        public: true

    smartgear.config.manager.framway_theme:
        class: WEM\SmartgearBundle\Config\Manager\FramwayTheme
        arguments:
            $translator: '@contao.translation.translator'
            $configuration: '@smartgear.config.framway_theme'
            $configurationManagerCore: '@smartgear.config.manager.core'
        public: true

    smartgear.config.manager.env_file.local:
        class: WEM\SmartgearBundle\Config\Manager\EnvFile
        arguments:
            $translator: '@contao.translation.translator'
            $configuration: '@smartgear.config.env_file'
            $configurationFilePath: '../.env.local'
        public: true

    smartgear.config.manager.local_config:
        class: WEM\SmartgearBundle\Config\Manager\LocalConfig
        arguments:
            $translator: '@contao.translation.translator'
            $configuration: '@smartgear.config.local_config'
            $configurationFilePath: '../config/config.yml'
        public: true

    smartgear.config.core:
        class: WEM\SmartgearBundle\Config\Core
        public: true

    smartgear.config.blog:
        class: WEM\SmartgearBundle\Config\Blog
        public: true

    smartgear.config.framway:
        class: WEM\SmartgearBundle\Config\Framway
        public: true

    smartgear.config.framway_theme:
        class: WEM\SmartgearBundle\Config\FramwayTheme
        public: true

    smartgear.config.env_file:
        class: WEM\SmartgearBundle\Config\EnvFile
        public: true

    smartgear.config.local_config:
        class: WEM\SmartgearBundle\Config\LocalConfig
        public: true

    smartgear.backup.backup_manager:
        class: WEM\SmartgearBundle\Backup\BackupManager
        arguments:
            $rootDir: '%kernel.project_dir%'
            $backupDirectory: 'assets/backups'
            $databaseBackupDirectory: 'var/backups' # defined in contao source files, with no ways to access it from outside
            $commandUtil: '@smartgear.classes.command.util'
            $databaseBackupManager: '@contao.doctrine.backup_manager'
            $translator: '@contao.translation.translator'
            $artifactsToBackup:
                - 'composer.json'
                - 'assets/smartgear'
                - 'files'
                - 'templates'
            $tablesToIgnore:
                - '+tl_db_cache'
                - '+tl_log'
                - '+tl_undo'
                - '+tl_version'
                - '+tl_search'
                - '+tl_search_index'
                - '+tl_sm_backup'
        public: true

    smartgear.update.update_manager:
        class: WEM\SmartgearBundle\Update\UpdateManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $backupManager: '@smartgear.backup.backup_manager'
            $migrations: 
                - '@smartgear.migrations.v1_0_0.m202203231730.migration'
        public: true

    smartgear.model.backup:
        class: WEM\SmartgearBundle\Model\Backup
        public: true

    ############ API SMARTGEAR V1 ############

    smartgear.api.smartgear.v1.api:
        class: WEM\SmartgearBundle\Api\Smartgear\V1\Api
        arguments:
            $coreConfigurationManager: '@smartgear.config.manager.core'
            $securityApiKey: '@smartgear.classes.api.security.api_key'
            $securityToken: '@smartgear.classes.api.security.token'
        public: true
    
    ############ API BACKUP V1 ############

    smartgear.api.backup.v1.api:
        class: WEM\SmartgearBundle\Api\Backup\V1\Api
        arguments:
            $translator: '@contao.translation.translator'
            $backupManager : '@smartgear.backup.backup_manager'
            $listResultToListResponseMapper: '@smartgear.api.backup.v1.model.mapper.list_result_to_list_response'
            $createResultToCreateResponseMapper: '@smartgear.api.backup.v1.model.mapper.create_result_to_create_response'
        public: true

    smartgear.api.backup.v1.model.list_response:
        class: WEM\SmartgearBundle\Api\Backup\V1\Model\ListResponse
        public: true

    smartgear.api.backup.v1.model.create_response:
        class: WEM\SmartgearBundle\Api\Backup\V1\Model\CreateResponse
        public: true

    smartgear.api.backup.v1.model.mapper.list_result_to_list_response:
        class: WEM\SmartgearBundle\Api\Backup\V1\Model\Mapper\ListResultToListResponse
        public: true

    smartgear.api.backup.v1.model.mapper.create_result_to_create_response:
        class: WEM\SmartgearBundle\Api\Backup\V1\Model\Mapper\CreateResultToCreateResponse
        public: true
    
    ############ API UPDATE V1 ############

    smartgear.api.update.v1.api:
        class: WEM\SmartgearBundle\Api\Update\V1\Api
        arguments:
            $updateManager : '@smartgear.update.update_manager'
            $listResultToListResponseMapper: '@smartgear.api.update.v1.model.mapper.list_result_to_list_response'
            $updateResultToUpdateResponseMapper: '@smartgear.api.update.v1.model.mapper.update_result_to_update_response'
        public: true

    smartgear.api.update.v1.model.list_response:
        class: WEM\SmartgearBundle\Api\Update\V1\Model\ListResponse
        public: true

    smartgear.api.update.v1.model.update_response:
        class: WEM\SmartgearBundle\Api\Update\V1\Model\UpdateResponse
        public: true

    smartgear.api.update.v1.model.mapper.list_result_to_list_response:
        class: WEM\SmartgearBundle\Api\Update\V1\Model\Mapper\ListResultToListResponse
        public: true

    smartgear.api.update.v1.model.mapper.update_result_to_update_response:
        class: WEM\SmartgearBundle\Api\Update\V1\Model\Mapper\UpdateResultToUpdateResponse
        public: true
    
