services:
    smartgear.backend.backupservice:
        class: WEM\SmartgearBundle\Backup\BackupService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true
    smartgear.backend.updater:
        class: WEM\SmartgearBundle\Updater\UpdaterService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true

    smartgear.classes.directories_synchronizer.templates.rsce:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $directoryToSynchronizeFrom: './web/bundles/wemsmartgear/contao_files/templates/rsce'
            $directoryToSynchronizeTo: './templates/rsce'
        public: true

    smartgear.classes.directories_synchronizer.tiny_mce.plugins:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $directoryToSynchronizeFrom: './web/bundles/wemsmartgear/contao_files/assets/tinymce4/js/plugins'
            $directoryToSynchronizeTo: './assets/tinymce4/js/plugins'
        public: true

    smartgear.classes.config.manager.core:
        class: WEM\SmartgearBundle\Classes\Config\Manager
        arguments:
            $configuration: '@smartgear.config.core'
            $configurationFilePath: 'assets/smartgear/config_core.json'
        public: true

    smartgear.classes.config.manager.framway:
        class: WEM\SmartgearBundle\Classes\Config\ManagerFramway
        arguments:
            $configuration: '@smartgear.config.framway'
            $configurationManagerCore: '@smartgear.classes.config.manager.core'
        public: true

    smartgear.config.core:
        class: WEM\SmartgearBundle\Config\Core
        public: true

    smartgear.config.framway:
        class: WEM\SmartgearBundle\Config\Framway
        public: true

    smartgear.backend.module.core.block:
        class: WEM\SmartgearBundle\Backend\Module\Core\Block
        arguments:
            $configurationStepManager: '@smartgear.backend.module.core.configuration_step_manager'
        public: true

    smartgear.backend.module.core.configuration_step_manager:
        class: WEM\SmartgearBundle\Classes\Backend\ConfigurationStepManager
        arguments:
            $configurationManager: '@smartgear.classes.config.manager.core'
            $module: 'core'
            $type: 'core'
            $steps: 
                - '@smartgear.backend.module.core.configuration_step.general'
                - '@smartgear.backend.module.core.configuration_step.framway_retrieval'
                - '@smartgear.backend.module.core.configuration_step.framway_configuration'
                - '@smartgear.backend.module.core.configuration_step.general'
        public: true

    smartgear.backend.module.core.configuration_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\General
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.classes.config.manager.core'
        public: true

    smartgear.backend.module.core.configuration_step.framway_retrieval:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\FramwayRetrieval
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.classes.config.manager.core'
        public: true

    smartgear.backend.module.core.configuration_step.framway_configuration:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\FramwayConfiguration
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.classes.config.manager.core'
            $configurationManagerFramway: '@smartgear.classes.config.manager.framway'
            $templateSynchronizer: '@smartgear.classes.directories_synchronizer.templates.rsce'
            $tinyMCEPluginsSynchronizer: '@smartgear.classes.directories_synchronizer.tiny_mce.plugins'
        public: true
