services:
    smartgear.backend.backupservice:
        class: WEM\SmartgearBundle\Backup\BackupService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true
    smartgear.backend.updater:
        class: WEM\SmartgearBundle\Updater\UpdaterService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true

    smartgear.classes.directories_synchronizer.templates.rsce:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates/rsce'
            $destinationDirectory: 'templates/rsce'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.templates.smartgear:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates/smartgear'
            $destinationDirectory: 'templates/smartgear'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.templates.general:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/templates'
            $destinationDirectory: 'templates'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: false
        public: true

    smartgear.classes.directories_synchronizer.tiny_mce.plugins:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/assets/tinymce4/js/plugins'
            $destinationDirectory: 'assets/tinymce4/js/plugins'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.outdated_browser:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/files/vendor/outdatedbrowser'
            $destinationDirectory: 'files/vendor/outdatedbrowser'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.classes.directories_synchronizer.tarte_au_citron:
        class: WEM\SmartgearBundle\Classes\DirectoriesSynchronizer
        arguments:
            $sourceDirectory: 'public/bundles/wemsmartgear/contao_files/files/vendor/tarteaucitron'
            $destinationDirectory: 'files/vendor/tarteaucitron'
            $rootDir: '%kernel.project_dir%'
            $manageSubfolders: true
        public: true

    smartgear.config.manager.core:
        class: WEM\SmartgearBundle\Classes\Config\Manager\ManagerJson
        arguments:
            $configuration: '@smartgear.config.core'
            $configurationFilePath: './assets/smartgear/config_core.json'
        public: true

    smartgear.classes.analyzer.htaccess:
        class: WEM\SmartgearBundle\Classes\Analyzer\Htaccess
        arguments:
            $htAccessFilePath: './.htaccess'
        public: true

    smartgear.config.manager.framway:
        class: WEM\SmartgearBundle\Config\Manager\Framway
        arguments:
            $configuration: '@smartgear.config.framway'
            $configurationManagerCore: '@smartgear.config.manager.core'
        public: true

    smartgear.config.manager.env_file.local:
        class: WEM\SmartgearBundle\Config\Manager\EnvFile
        arguments:
            $configuration: '@smartgear.config.env_file'
            $configurationFilePath: '../.env.local'
        public: true

    smartgear.config.manager.local_config:
        class: WEM\SmartgearBundle\Config\Manager\LocalConfig
        arguments:
            $configuration: '@smartgear.config.local_config'
            $configurationFilePath: '../config/config.yml'
        public: true

    smartgear.config.core:
        class: WEM\SmartgearBundle\Config\Core
        public: true

    smartgear.config.framway:
        class: WEM\SmartgearBundle\Config\Framway
        public: true

    smartgear.config.env_file:
        class: WEM\SmartgearBundle\Config\EnvFile
        public: true

    smartgear.config.local_config:
        class: WEM\SmartgearBundle\Config\LocalConfig
        public: true

    smartgear.backend.module.core.dashboard:
        class: WEM\SmartgearBundle\Backend\Module\Core\Dashboard
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $module: 'core'
            $type: 'core'
            $configurationEnvFileManager: '@smartgear.config.manager.env_file.local'
            $htaccessAnalyzer: '@smartgear.classes.analyzer.htaccess'
        public: true

    smartgear.backend.module.core.block:
        class: WEM\SmartgearBundle\Backend\Module\Core\Block
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $configurationStepManager: '@smartgear.backend.module.core.configuration_step_manager'
            $resetStepManager: '@smartgear.backend.module.core.reset_step_manager'
            $dashboard: '@smartgear.backend.module.core.dashboard'
        public: true

    smartgear.backend.module.core.configuration_step_manager:
        class: WEM\SmartgearBundle\Classes\Backend\ConfigurationStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $module: 'core'
            $type: 'core'
            $stepSessionKey: 'sg_core_install_step'
            $steps: 
                - '@smartgear.backend.module.core.configuration_step.general'
                - '@smartgear.backend.module.core.configuration_step.framway_retrieval'
                - '@smartgear.backend.module.core.configuration_step.framway_configuration'
                - '@smartgear.backend.module.core.configuration_step.website'
        public: true

    smartgear.backend.module.core.reset_step_manager:
        class: WEM\SmartgearBundle\Backend\Module\Core\ResetStepManager
        arguments:
            $configurationManager: '@smartgear.config.manager.core'
            $module: 'core'
            $type: 'core'
            $stepSessionKey: 'sg_core_reset_step'
            $steps: 
                - '@smartgear.backend.module.core.reset_step.general'
        public: true

    smartgear.backend.module.core.configuration_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\General
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.config.manager.core'
            $localConfigManager: '@smartgear.config.manager.local_config'
        public: true

    smartgear.backend.module.core.configuration_step.framway_retrieval:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\FramwayRetrieval
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.core.configuration_step.framway_configuration:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\FramwayConfiguration
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.config.manager.core'
            $configurationManagerFramway: '@smartgear.config.manager.framway'
            $templateRSCESynchronizer: '@smartgear.classes.directories_synchronizer.templates.rsce'
            $templateSmartgearSynchronizer: '@smartgear.classes.directories_synchronizer.templates.smartgear'
            $templateGeneralSynchronizer: '@smartgear.classes.directories_synchronizer.templates.general'
            $tinyMCEPluginsSynchronizer: '@smartgear.classes.directories_synchronizer.tiny_mce.plugins'
            $tarteAuCitronSynchronizer: '@smartgear.classes.directories_synchronizer.tarte_au_citron'
            $outdatedBrowserSynchronizer: '@smartgear.classes.directories_synchronizer.outdated_browser'
        public: true

    smartgear.backend.module.core.configuration_step.website:
        class: WEM\SmartgearBundle\Backend\Module\Core\ConfigurationStep\Website
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.config.manager.core'
        public: true

    smartgear.backend.module.core.reset_step.general:
        class: WEM\SmartgearBundle\Backend\Module\Core\ResetStep\General
        arguments:
            $module: 'core'
            $type: 'core'
            $configurationManager: '@smartgear.config.manager.core'
            $localConfigManager: '@smartgear.config.manager.local_config'
            $templatesDirs: 
                - 'templates/rsce'
                - 'templates/smartgear'
        public: true
