services:
    smartgear.backend.backupservice:
        class: WEM\SmartgearBundle\Backup\BackupService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true
    smartgear.backend.updater:
        class: WEM\SmartgearBundle\Updater\UpdaterService
        arguments:
            - '@contao.framework'
            - '@filesystem'
            - '@contao.slug.generator'
            - '@request_stack'
        public: true

    smartgear.classes.config.manager.core:
        class: WEM\SmartgearBundle\Classes\Config\Manager
        arguments:
            $configuration: '@smartgear.classes.config.core'
            $configurationFilePath: 'assets/smartgear/config_core.json'
        public: true

    smartgear.classes.config.core:
        class: WEM\SmartgearBundle\Classes\Config\Core
        public: true
